wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true

server:
  port: 8080

restClient:
  proxy:
    shopUrl: http://localhost:8090/relay/v1/shop
    agencyUrl: http://localhost:8090/relay/v1/agency

