server:
  port: 8888

spring:
  profiles:
    active: production
  mongodb:
    embedded:
      version: 3.5.5
  rabbitmq:
    host: 127.0.0.1
    port: 5672

hello:
  sha: aaaaaa
  world: Hello World! from Delivery-Info-Service ${hello.sha}.from Here