wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true

server:
  port: 8888

restClient:
  proxy:
    shopUrl: http://localhost:8090/relay/v1/shop
    agencyUrl: http://localhost:8090/relay/v1/agency


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      primary:
        database: inbobwetrust
        uri: mongodb://localhost:27017
      secondary:
        uri: mongodb://localhost:27018
        database: inbobwetrust
