spring.data.mongodb:
  #  port: 27017
  #  host: 127.0.0.1
  port: 12345
  host: 127.0.0.1

autoconfigure:
  exclude: org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
