server:
  port: 8888

spring:
  data:
    mongodb:
      database: inbobwetrust
      uri: mongodb://localhost:27017

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true

restClient:
  proxy:
    shopUrl: http://localhost:8090/relay/v1/shop
    agencyUrl: http://localhost:8090/relay/v1/agency

