wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true


spring:
  data:
    mongodb:
      primary:
        database: inbob
        uri: mongodb://localhost:27017
      secondary:
        database: inbob
        uri: mongodb://localhost:27018

restClient:
  proxy:
    shopUrl: http://localhost:${wiremock.server.port}/relay/v1/shop
    agencyUrl: http://localhost:${wiremock.server.port}/relay/v1/agency

db-ports:
  primary: ${spring.data.mongodb.primary.uri.port}
  secondary: ${spring.data.mongodb.secondary.uri.port}

