wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true


spring:
  data:
    mongodb:
      primary:
        database: inbob
        uri: mongodb://localhost:27017
      secondary:
        database: inbob
        uri: mongodb://localhost:28017

