version: "3.4"
services:
  delivery-info-service:
    image: inbobwetrust/delivery-info-service:v.0.0.1
    environment:
      - COMMAND_LINE_ARGS_BEFORE=-Dspring.data.mongodb.primary.database=inbobwetrust -Dspring.data.mongodb.primary.uri=mongodb://host.docker.internal:27017 -Dspring.data.mongodb.secondary.database=inbobwetrust -Dspring.data.mongodb.secondary.uri=mongodb://host.docker.internal:27018
      - COMMAND_LINE_ARGS_AFTER=--spring.profiles.active=loadtest
    ports:
      - "8080:8080"
    networks:
      - inbobwetrust

  mongo-primary:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - inbobwetrust
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok'| grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234

  mongo-secondary:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - inbobwetrust
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok'| grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234

  wiremock-relay-service:
    image: wiremock/wiremock
    volumes:
      - ./wiremock/ __files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    ports:
      - "8090:8080"
    networks:
      - inbobwetrust

  prometheus:
    image: prom/prometheus
    volumes:
      - /Users/joohyuk/dev/github.com/in-bob-we-trust/k6-test/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - inbobwetrust

  k6:
    image: loadimpact/k6:latest
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - inbobwetrust
    depends_on:
      - delivery-info-service
      - mongo-secondary
      - mongo-primary
      - wiremock-relay-service

networks:
  inbobwetrust:
    driver: bridge

