version: "3.4"
services:
  delivery-info-service:
    image: beanskobe/delivery-info-service
    environment:
      - COMMAND_LINE_ARGS_BEFORE=-Dspring.data.mongodb.primary.database=inbobwetrust -Dspring.data.mongodb.primary.uri=mongodb://host.docker.internal:27017 -Dspring.data.mongodb.secondary.database=inbobwetrust -Dspring.data.mongodb.secondary.uri=mongodb://host.docker.internal:27018
      - COMMAND_LINE_ARGS_AFTER=--spring.profiles.active=local
    ports:
      - "8888:8888"
    networks:
      - inbobwetrust

  mongo-info-database:
    image: mongo
    ports:
      - "37017:27017"
    networks:
      - inbobwetrust
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok'| grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  delivery-relay-service:
    image: beanskobe/delivery-relay-service
    environment:
      - COMMAND_LINE_ARGS_BEFORE=-Dspring.data.mongodb.database=relay -Dspring.data.mongodb.uri=mongodb://host.docker.internal:37017
      - COMMAND_LINE_ARGS_AFTER=--spring.profiles.active=local
    ports:
      - "8090:8090"
    networks:
      - inbobwetrust

  mongo-relay:
    image: mongo
    ports:
      - "28017:27017"
    networks:
      - inbobwetrust
    restart: always
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok'| grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  inbobwetrust:
    driver: bridge

