wiremock:
  server:
    httpsPort: -1
  reset-mappings-after-each-test: true


spring:
  data:
    mongodb:
      database: inbob
      uri: mongodb://localhost:27017

restClient:
  proxy:
    shopUrl: http://localhost:${wiremock.server.port}/relay/v1/shop
    agencyUrl: http://localhost:${wiremock.server.port}/relay/v1/agency
