name: Build Image delivery-info-service

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE_BUILD_DIR_PAIR: [ [ 'delivery-info-service', './delivery-info-service' ] ]
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew delivery-info-service:build

      - name: 로그인 to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{  env.DOCKERHUB_TOKEN }}

      - name: 도커 이미지빌드 w/ version
        if: success()
        run: docker image build -t ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:${GITHUB_SHA::7} ${{matrix.IMAGE_BUILD_DIR_PAIR[1]}}
      - name: 도커 이미지 push w/ version
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:${GITHUB_SHA::7}

      - name: 도커 이미지빌드 latest
        if: success()
        run: docker image build -t ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:latest ${{matrix.IMAGE_BUILD_DIR_PAIR[1]}}
      - name: 도커 이미지 push latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:latest

