name: CI delivery-info-service

on: [ push , pull_request ]
jobs:
  #----------------------------------------------------------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        TEST_COMMAND: [ '--info delivery-info-service:integrationTest', '--info delivery-info-service:test' , '--info :delivery-info-service:generateJacocoTestCoverage' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew ${{ matrix.TEST_COMMAND }}

  #----------------------------------------------------------------------------------------------------------
  build:
    if: ${{ success() }}
    needs: test
    strategy:
      fail-fast: false
      matrix:
        IMAGE_BUILD_DIR_PAIR: [ [ 'delivery-info-service', './delivery-info-service' ] ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew delivery-info-service:build

      - name: 로그인 to Docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 도커 이미지빌드 w/ version
        if: success()
        run: docker image build -t ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:${GITHUB_SHA::7} ${{matrix.IMAGE_BUILD_DIR_PAIR[1]}}
      - name: 도커 이미지 push w/ version
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:${GITHUB_SHA::7}

      - name: 도커 이미지빌드 latest
        if: success()
        run: docker image build -t ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:latest ${{matrix.IMAGE_BUILD_DIR_PAIR[1]}}
      - name: 도커 이미지 push latest
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push ${{ secrets.DOCKER_HUB_PASSWORD }}/${{matrix.IMAGE_BUILD_DIR_PAIR[0]}}:latest

