name: selfhosted runner delivery-info-service

on:
  push:
    branches:
      - \#142-docker-compose-를-활용한-서버-성능테스트
jobs:
  #----------------------------------------------------------------------------------------------------------
  set_up:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: joschi/setup-jdk@v2
        with:
          java-version: '11'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle BootJar
        if: success()
        run: ./gradlew :delivery-info-service:build --x test --x integrationTest

      - name: Docker clean
        if: success()
        run: docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)  || true

      - name: Docker build delivery-info-service Image
        if: success()
        run: docker image build -t inbobwetrust/delivery-info-service:loadtest ./delivery-info-service

      - name: Docker compose up
        if: success()
        run: docker-compose -f ./k6-test/docker-compose-actions.yml up -d

      - name: Verify > Sleep for 20 seconds
        run: sleep 20
      - name: Verify > Docker run wiremock
        if: success()
        run: curl --max-time 10 http://localhost:8090/__admin/mappings
      - name: Verify > Docker run wiremock
        if: success()
        run: curl  --max-time 10  http://localhost:8888/api/delivery

      - name: K6 > Loadtest > run test
        run: docker run --add-host=host.docker.internal:host-gateway -i loadimpact/k6 run - <./k6-test/k6-scripts/test1.js


