name: LoadTest delivery-info-service

on:
  push:
    branches:
      - \#142-docker-compose-를-활용한-서버-성능테스트
jobs:
  #----------------------------------------------------------------------------------------------------------
  load_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle BootJar
        if: success()
        run: ./gradlew :delivery-info-service:bootJar --exclude-task test

      - name: Docker create bridge
        if: success()
        run: docker network create -d bridge inbobwetrust

      - name: Docker build delivery-info-service Image
        if: success()
        run: docker image build -t inbobwetrust/delivery-info-service:${GITHUB_SHA::7} ./delivery-info-service
      - name: Docker run delivery-info-service
        if: success()
        run: docker run -d -p 8080:8080 --network=inbobwetrust  -e COMMAND_LINE_ARGS_BEFORE='-Dspring.data.mongodb.primary.database=inbobwetrust -Dspring.data.mongodb.primary.uri=mongodb://localhost:27017 -Dspring.data.mongodb.secondary.database=inbobwetrust -Dspring.data.mongodb.secondary.uri=mongodb://localhost:27018'   -e COMMAND_LINE_ARGS_AFTER='--spring.profiles.active=loadTest'   beanskobe/delivery-info-service

      - name: Docker run primary mongo
        if: success()
        run: docker run -d --network=inbobwetrust -d -p 27017:27017 mongo


      - name: Docker run secondary mongo
        if: success()
        run: docker run -d --network=inbobwetrust -d -p 27018:27017 mongo

      - name: Docker run wiremock
        if: success()
        run: |
          docker run -d --network=inbobwetrust -p 8090:8080 -v ~/dev/github.com/in-bob-we-trust/k6-test/wiremock/__files:/home/wiremock/__files  -v ~/dev/github.com/in-bob-we-trust/k6-test/wiremock/mappings:/home/wiremock/mappings wiremock/wiremock

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Docker run wiremock
        if: success()
        run: curl http://localhost:8090/__admin/mappings

      - name: Run local k6 test
        uses: k6io/action@v0.1
        with:
          filename: ./k6-test/k6-scripts/simple-delivery-get.js
