name: LoadTest delivery-info-service

on:
  push:
    branches:
      - \#142-docker-compose-를-활용한-서버-성능테스트
jobs:
  #----------------------------------------------------------------------------------------------------------
  load_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Start Logging
        run: echo Gradle Build Test Start

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle BootJar
        if: success()
        run: ./gradlew :delivery-info-service:bootJar --exclude-task test
      #
      - name: Build Docker Image
        if: success()
        run: docker image build -t inbobwetrust/delivery-info-service:${GITHUB_SHA::7} ./delivery-info-service

      - name: Docker-Compose up
        if: success()
        run: GITHUB_SHA_IMAGE_TAG=${GITHUB_SHA::7} docker-compose -f ./k6-test/docker-compose-actions.yml up -d

      - name: Test localhost connection
        run: curl http://localhost:8080/actuator/metrics

      - name: Test local connection
        run: curl http://localhost:8080/api/delivery

      - name: Test host.docker.internal connection
        run: curl http://host.docker.internal:8080/actuator/metrics

      - name: Test host.docker.internal connection
        run: curl http://host.docker.internal:8080/api/delivery

      - name: Run local k6 test
        uses: k6io/action@v0.1
        with:
          filename: ./k6-test/k6-scripts/simple-delivery-get.js

#  bootjar
#  build image
#  docker-compose -f ./k6-test/docker-compose.yml up -d
#  run with image
